site_name: Preamp project
nav:
  - Home: index.md
  - Requirements: generated/doorstop/REQ.md
  - Specification: generated/doorstop/SPEC.md
  - Testing: generated/doorstop/TST.md
theme:
  name: solar
extra_css:
  - assets/css/preamp-doorstop.css
extra_javascript:
  - assets/js/preamp-doorstop.js
